import images from './images/images.js'

const data = [
  {
    name: 'Spotrybe',
    img: images.imgSpotrybe,
    link: 'https://github.com/Ply3r/Projeto_Spotrybe/',
    type: 'fundamentos',
    favorite: true,
  },
  {
    name: 'Pokedex',
    img: images.imgPokedex,
    link: 'https://github.com/Ply3r/my-pokedex/',
    type: 'front',
    favorite: false,
  },
  {
    name: 'MoodStore',
    img: images.imgMoodStore,
    link: 'https://github.com/Ply3r/portifolio_antigo/projetos/loja_de_roupa/index.html',
    type: 'fundamentos',
    favorite: false,
  },
  {
    name: 'Timer',
    img: images.imgTimer,
    link: 'https://github.com/Ply3r/portifolio_antigo/projetos/timer/index.html',
    type: 'fundamentos',
    favorite: false,
  },
  {
    name: 'Netflix React',
    img: images.imgNetflix,
    link: 'https://github.com/Ply3r/netflix-react/',
    type: 'front',
    favorite: true,
  },
  {
    name: 'Yu-gi-oh',
    img: images.yugioh,
    link: 'https://github.com/Ply3r/yu-gi-oh',
    type: 'front',
    favorite: false,
  },
  {
    name: 'Trybe-Tunes',
    img: images.trybeTunes,
    link: 'https://github.com/Ply3r/trybe-tunes',
    type: 'front',
    favorite: true,
  },
  {
    name: 'MoodStore2.0',
    img: images.moodStore2,
    link: 'https://github.com/Ply3r/mood-store2.0/',
    type: 'front',
    favorite: true,
  },
  {
    name: 'Timer2.0',
    img: images.timer2,
    link: 'https://github.com/Ply3r/timer2.0/',
    type: 'front',
    favorite: true,
  },
  {
    name: 'Trybe wallet',
    img: images.trWallet,
    link: 'https://github.com/Ply3r/trybe-wallet/',
    type: 'front',
    favorite: true,
  },
  {
    name: 'Solar System',
    img: images.solarSystem,
    link: 'https://github.com/Ply3r/Solar-System/',
    type: 'front',
    favorite: true,
  },
  {
    name: 'Star Wars 3D',
    img: images.starWars,
    link: 'https://github.com/Ply3r/star-wars-3d/',
    type: 'front',
    favorite: true,
  },
  {
    name: 'App de receitas',
    img: images.recipeApp,
    link: 'https://github.com/Ply3r/recipes-app',
    type: 'front',
    favorite: true,
  },
  {
    name: 'Flappy Bird',
    img: images.flappyBird,
    link: 'https://github.com/Ply3r/flappy-bird',
    type: 'back',
    favorite: true,
  },
  {
    name: 'Snake',
    img: images.snake,
    link: 'https://github.com/Ply3r/snake',
    type: 'back',
    favorite: true,
  },
]

export default data;